### ISSUE TITLE
Problème ressource "mailparser": erreur mail avec pj

### ISSUE THREAD

**Issue by abarrau** [lunarok/jeedom_maillistener#3]
Cédric,
Il semble qu'il y ai un problème dans l'appel des "mimes" depuis "mailparser", pour la récupération du nom des fichiers attachés d'un mail. 

Voici une correction possible : 
- modifier la fonction "_generateFileName" dans le fichier "resources\node_modules\mail-listener3\node_modules\mailparser\lib\mailparser.js"
- ligne 1407 : remplacer : 
> defaultExt = mime.extension(contentType);

par 
> defaultExt = mime.getExtension(contentType);

Or ce fichier ne fait pas directement partie de ton projet et si l'on analyse plus loin, ça se complique. 
Je ne peux pas faire de demande de mise à jour du fichier, car il semblerait que pour ce fichier, on ne soit pas du tout sur la bonne version. 

** Petite synthèse de mon analyse : 
Dans les ressources du projet, la ressource "mail-listener3" implémente une ressource "mailparser". 
J'ai constaté que ce "mailparser" était disponible sous : 
- resources\node_modules\mail-listener3\node_modules\
- ou resources\node_modules\mailparser
mais pas avec la même version, la 1ère en 0.4.6, la 2nde en 2.0.1. 

Or les fichiers utilisées sont ceux présents dans "resources\node_modules\mail-listener3\node_modules\mailparser\lib", (un sacré nombre de version d'écart), ce qui n'arrange rien, c'est que mail-listerner3 n'est plus maintenu. 

** Conclusion (?) : 
1/ mail-listener3 n'étant plus maintenue, soit lors de la génération du package, tu pourrais apporter la correction dans le fichier listé ci-dessus ; > simple et pérenne. 
2/ ou dans mail-listerner3 changer la valeur minimum de la ressource pour mailparser , mais cela a un impact important sur mail-listerner3.

En l'état, le mail avec PJ ne fonctionne pas si la correction n'est pas appliquée. 
Merci et bon courage. 

----- 
Pour info, voici l'erreur remontée dans "maillistener_node" :  

> /var/www/html/plugins/maillistener/resources/node_modules/mail-listener3/node_modules/mailparser/lib/mailparser.js:1408
defaultExt = mime.extension(contentType);
^
TypeError: mime.extension is not a function
at MailParser._generateFileName (/var/www/html/plugins/maillistener/resources/node_modules/mail-listener3/node_modules/mailparser/lib/mailparser.js:1408:27)
at MailParser._processStateHeader (/var/www/html/plugins/maillistener/resources/node_modules/mail-listener3/node_modules/mailparser/lib/mailparser.js:309:61)
at MailParser._process (/var/www/html/plugins/maillistener/resources/node_modules/mail-listener3/node_modules/mailparser/lib/mailparser.js:227:22)
at tryOnImmediate (timers.js:534:15)
at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by lunarok** [comment]
Pour tester : https://github.com/lunarok/jeedom_maillistener/commit/9769ad3bf5b6f5d5a15019eda764683befa4c02f

**Comment by abarrau** [comment]
Merci Cédric pour cette correction. 
J'ai modifié ta proposition qui fonction maintenant. 

Condition : 
- relancer les dépendances
- relancer le démon
